# Generated by Django 2.0.5 on 2018-05-10 19:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='background')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='photos')),
                ('show', models.BooleanField(default=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('background_color', models.CharField(default='ffffff', max_length=6, validators=[django.core.validators.RegexValidator('^[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, a, b, c, d, e ,f]{6}$')])),
                ('menu_font', models.URLField(default='https://fonts.googleapis.com/css?family=Karla:400,400i,700,700i')),
                ('menu_font_color', models.CharField(default='ffffff', max_length=6, validators=[django.core.validators.RegexValidator('^[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, a, b, c, d, e ,f]{6}$')])),
                ('menu_font_color_hover', models.CharField(default='fc4620', max_length=6, validators=[django.core.validators.RegexValidator('^[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, a, b, c, d, e ,f]{6}$')])),
                ('page_font', models.URLField(default='https://fonts.googleapis.com/css?family=Karla:400,400i,700,700i')),
                ('page_font_color', models.CharField(default='000000', max_length=6, validators=[django.core.validators.RegexValidator('^[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, a, b, c, d, e ,f]{6}$')])),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.BackgroundImage')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.Settings'),
        ),
        migrations.AddField(
            model_name='album',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.Settings'),
        ),
    ]
